//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager_tbl
    {
        public int Code { get; set; }
        public string Name_user { get; set; }
        public string ID_user { get; set; }
        public string Password { get; set; }
    }
}
