//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendingHistory_tbl
    {
        public int ID_sendingHistory { get; set; }
        public int ID_category { get; set; }
        public int ID_emailRequest { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_sendingAdjustmentStatus { get; set; }
        public bool IsSentAutomat { get; set; }
        public Nullable<int> SentFrom { get; set; }
        public Nullable<float> Precision { get; set; }
    
        public virtual Category_tbl Category_tbl { get; set; }
        public virtual Category_tbl Category_tbl1 { get; set; }
        public virtual EmailRequest_tbl EmailRequest_tbl { get; set; }
        public virtual SendingAdjustmentStatus_tbl SendingAdjustmentStatus_tbl { get; set; }
    }
}
