//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordPerCategory_tbl
    {
        public int ID_wordPerCategory { get; set; }
        public int ID_word { get; set; }
        public int ID_category { get; set; }
        public Nullable<int> AmountOfUse { get; set; }
        public Nullable<float> MatchPercentage { get; set; }
    
        public virtual Category_tbl Category_tbl { get; set; }
        public virtual Word_tbl Word_tbl { get; set; }
    }
}
