//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordPerRequest_tbl
    {
        public int Id_wordPerRequest { get; set; }
        public int Request_id { get; set; }
        public int word_id { get; set; }
    
        public virtual EmailRequest_tbl EmailRequest_tbl { get; set; }
        public virtual Word_tbl Word_tbl { get; set; }
    }
}
